### ISSUE TITLE
Define the preferred way of writing custom adapters

### ISSUE THREAD

**Issue by duizendnegen** [LevelbossMike/ember-deploy#14]
Hi, I'm planning to in the near future write an adapter for Azure, their CDN & their key/value store. What's the preferred way of releasing it to the greater public, too? Shall I contribute to this project or create a separate add-on? If the latter is preferred, would you want to maintain a list of existing OSS add-ons?

**Comment by LevelbossMike** [comment]
I extracted the default adapters into addons and updated the README. Please let me know if I can be of any more help with your Azure adapter.
